#!/usr/bin/env python3
"""Set author/company metadata on Office and PDF files so they carry the identity the user chose
for the project (asked once per project), not the generating tool (python-docx, openpyxl, python-pptx, reportlab, Claude, ...).

Usage:
  python set_doc_metadata.py FILE_OR_DIR [...] --company "Example Corp" [--author "Jane Doe"]
                             [--title "..."]
  python set_doc_metadata.py FILE_OR_DIR [...] --company ""        # no company
  python set_doc_metadata.py FILE_OR_DIR [...] --strip-only        # remove fingerprints only
  python set_doc_metadata.py FILE_OR_DIR [...] --check             # report, change nothing

- .docx/.xlsx/.pptx (and .docm/.xlsm/.pptm): rewrites docProps/core.xml and docProps/app.xml in place.
- .pdf: needs PyMuPDF (fitz); sets author/creator/producer.
- --check: report current metadata and flag tool/AI fingerprints, change nothing.
Zero dependencies for Office files. Keeps every other zip member byte-identical.
"""
import argparse, datetime, os, re, shutil, sys, tempfile, zipfile
from xml.sax.saxutils import escape

OFFICE = {'.docx': 'Microsoft Office Word', '.docm': 'Microsoft Office Word',
          '.xlsx': 'Microsoft Excel', '.xlsm': 'Microsoft Excel',
          '.pptx': 'Microsoft Office PowerPoint', '.pptm': 'Microsoft Office PowerPoint'}
FINGERPRINT = re.compile(r'python-docx|openpyxl|python-pptx|xlsxwriter|reportlab|docx4j|pandoc|claude|anthropic|chatgpt|openai|\bai\b|generated by', re.I)


def _set(xml, tag, value, ns_decl=None):
    """Replace <tag ...>..</tag> (or self-closing) with value; append before the root close tag if missing."""
    v = escape(value)
    pat = re.compile(r'<%s(\s[^>]*)?/>|<%s(\s[^>]*)?>.*?</%s>' % (tag, tag, tag), re.S)
    attrs = ' xsi:type="dcterms:W3CDTF"' if tag.startswith('dcterms:') else ''
    new = '<%s%s>%s</%s>' % (tag, attrs, v, tag)
    if pat.search(xml):
        return pat.sub(new, xml, count=1)
    root_close = xml.rfind('</')
    return xml[:root_close] + new + xml[root_close:]


def _drop(xml, tag):
    return re.sub(r'<%s(\s[^>]*)?/>|<%s(\s[^>]*)?>.*?</%s>' % (tag, tag, tag), '', xml, flags=re.S)


def office(path, author, company, title, check, strip_only=False):
    app_name = OFFICE[os.path.splitext(path)[1].lower()]
    with zipfile.ZipFile(path) as z:
        names = z.namelist()
        core = z.read('docProps/core.xml').decode('utf-8') if 'docProps/core.xml' in names else None
        app = z.read('docProps/app.xml').decode('utf-8') if 'docProps/app.xml' in names else None
    if check:
        blob = (core or '') + (app or '')
        hits = sorted(set(m.group(0) for m in FINGERPRINT.finditer(blob)))
        c1 = re.sub(r'\s+', ' ', core or 'MISSING')[:400]; a1 = re.sub(r'\s+', ' ', app or 'MISSING')[:300]
        print("%s\n  core: %s\n  app: %s\n  fingerprints: %s" % (path, c1, a1, hits or 'none'))
        return
    now = datetime.datetime.now(datetime.timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')
    if core is None:
        raise SystemExit(f"{path}: no docProps/core.xml (not an Office Open XML file?)")
    if not strip_only:
        core = _set(core, 'dc:creator', author)
        core = _set(core, 'cp:lastModifiedBy', author)
    else:
        for t in ('dc:creator', 'cp:lastModifiedBy'):
            m = re.search(r'<%s[^>]*>(.*?)</%s>' % (t, t), core, re.S)
            if m and FINGERPRINT.search(m.group(1)):
                core = _set(core, t, '')
    for t in ('dc:description', 'cp:keywords', 'dc:subject', 'cp:category'):
        m = re.search(r'<%s[^>]*>(.*?)</%s>' % (t, t), core, re.S)
        if m and FINGERPRINT.search(m.group(1)):
            core = _drop(core, t)
    if title:
        core = _set(core, 'dc:title', title)
    core = _set(core, 'dcterms:modified', now)
    if '<dcterms:created' not in core:
        core = _set(core, 'dcterms:created', now)
    if app is not None:
        app = _set(app, 'Application', app_name)
        if not strip_only:
            app = _set(app, 'Company', company)
        app = _drop(app, 'Template') if re.search(r'<Template>[^<]*(python|openpyxl)', app, re.I) else app
    fd, tmp = tempfile.mkstemp(suffix='.tmp', dir=os.path.dirname(os.path.abspath(path))); os.close(fd)
    try:
        with zipfile.ZipFile(path) as src, zipfile.ZipFile(tmp, 'w', zipfile.ZIP_DEFLATED) as dst:
            for info in src.infolist():
                data = src.read(info.filename)
                if info.filename == 'docProps/core.xml': data = core.encode('utf-8')
                elif info.filename == 'docProps/app.xml' and app is not None: data = app.encode('utf-8')
                dst.writestr(info, data)
        shutil.move(tmp, path)
    finally:
        if os.path.exists(tmp): os.remove(tmp)
    print("set  %s  (%s)" % (path, "fingerprints stripped only" if strip_only else "author=%s, company=%s" % (author, company or "(blank)")))


def pdf(path, author, company, title, check, strip_only=False):
    try:
        import fitz
    except ImportError:
        print(f"skip {path}: PyMuPDF not installed (pip install pymupdf)"); return
    doc = fitz.open(path); meta = dict(doc.metadata or {})
    if check:
        hits = sorted(set(m.group(0) for v in meta.values() if v for m in FINGERPRINT.finditer(str(v))))
        print(f"{path}\n  meta: {meta}\n  fingerprints: {hits or 'none'}"); doc.close(); return
    meta.update({'creator': 'Microsoft Word', 'producer': 'Microsoft Word'})
    if not strip_only:
        meta['author'] = author
    elif meta.get('author') and FINGERPRINT.search(meta['author']):
        meta['author'] = ''
    if title: meta['title'] = title
    for k in ('subject', 'keywords'):
        if meta.get(k) and FINGERPRINT.search(meta[k]): meta[k] = ''
    doc.set_metadata(meta)
    fd, tmp = tempfile.mkstemp(suffix='.pdf', dir=os.path.dirname(os.path.abspath(path))); os.close(fd)
    doc.save(tmp, garbage=3, deflate=True); doc.close(); shutil.move(tmp, path)
    print("set  %s" % path)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('paths', nargs='+')
    ap.add_argument('--author', default='')
    ap.add_argument('--company', default=None, help='required unless --check or --strip-only; "" for none')
    ap.add_argument('--strip-only', action='store_true', help='only remove tool/AI fingerprints')
    ap.add_argument('--title')
    ap.add_argument('--check', action='store_true')
    a = ap.parse_args()
    if not a.check and not a.strip_only and a.company is None:
        ap.error('choose the identity: --company "Example Corp" | --company "" | --strip-only '
                 '(ask the user once per project; see SKILL.md)')
    files = []
    for p in a.paths:
        if os.path.isdir(p):
            for root, _, fs in os.walk(p):
                files += [os.path.join(root, f) for f in fs if not f.startswith('~$')]
        else:
            files.append(p)
    for f in files:
        ext = os.path.splitext(f)[1].lower()
        if ext in OFFICE: office(f, a.author, a.company, a.title, a.check, a.strip_only)
        elif ext == '.pdf': pdf(f, a.author, a.company, a.title, a.check, a.strip_only)


if __name__ == '__main__':
    main()
