#!/usr/bin/env python3
"""Regenerate every catalog file from skills/*/SKILL.md.

Writes (all derived, never hand-edit them):
  skills.json                      manifest for agents, installers and the web catalog
  .claude-plugin/marketplace.json  Claude Code plugin marketplace (one plugin per skill + bundles)
  llms.txt                         llmstxt.org index for agents
  README.md                        only the block between the catalog markers and the stats line

Usage:
  python3 scripts/build-catalog.py                 # regenerate
  python3 scripts/build-catalog.py --check         # exit 1 if any generated file is stale
  python3 scripts/build-catalog.py --date 2026-10-06

Categories live in CATEGORIES below. A new skill must be added there, or the
build fails, so nothing ships uncategorised. Standard library only.
"""
import argparse
import datetime
import hashlib
import json
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SLUG = "mhshaon98/agent-skills"
BRANCH = "main"
REPO_URL = "https://github.com/" + SLUG
RAW_BASE = "https://raw.githubusercontent.com/%s/%s/" % (SLUG, BRANCH)
SITE_URL = "https://mhshaon98.github.io/agent-skills/"
# "agent-skills" itself is a reserved marketplace name in Claude Code, so the
# marketplace uses its own name. Install ids look like verify-work@dev-discipline.
MARKETPLACE = "dev-discipline"

CATEGORY_ORDER = ["workflow", "safety", "delegation", "formatting", "tooling"]
CATEGORY_TITLES = {
    "workflow": "Workflow",
    "safety": "Safety",
    "delegation": "Delegation",
    "formatting": "Formatting",
    "tooling": "Tooling",
}
CATEGORY_BLURBS = {
    "workflow": "Session continuity: start, hand off, track bugs, bootstrap projects.",
    "safety": "Verification, data safety, security and release gates.",
    "delegation": "Subagents, model routing, and second opinions from other providers.",
    "formatting": "Readable output and AI-slop cleanup.",
    "tooling": "Task-specific tools: CMS layer, process logging, usage reports.",
}
CATEGORIES = {
    "bug-ledger": "workflow",
    "call-handoff": "workflow",
    "new-project": "workflow",
    "session-start": "workflow",
    "update-handoff": "workflow",
    "app-audit": "safety",
    "compliance-check": "safety",
    "pre-release-review": "safety",
    "safe-data-write": "safety",
    "security-pass": "safety",
    "verify-work": "safety",
    "antigravity-bridge": "delegation",
    "astra-conductor": "delegation",
    "codex-bridge": "delegation",
    "cowork-relay": "delegation",
    "fable-conductor": "delegation",
    "spawn-agent": "delegation",
    "apply-richformat": "formatting",
    "slop-clean": "formatting",
    "client-cms": "tooling",
    "commissioning-logger": "tooling",
    "usage-here": "tooling",
}

# Which agent each skill is for. Default: both. Installers and agents must
# not put a skill into an agent it is not written for.
DEFAULT_TARGETS = ["claude", "codex"]
TARGETS = {
    "astra-conductor": ["codex"],
    "codex-bridge": ["claude"],
    "fable-conductor": ["claude"],
}
TARGET_NOTES = {("codex",): " *(Codex CLI only)*", ("claude",): " *(Claude Code only)*"}

README_START = "<!-- catalog:start (generated by scripts/build-catalog.py, do not edit) -->"
README_END = "<!-- catalog:end -->"
STATS_RE = re.compile(r"<!-- stats -->.*?<!-- /stats -->", re.S)


def read(path):
    with open(os.path.join(ROOT, path), "r", encoding="utf-8") as f:
        return f.read()


def write(path, text):
    full = os.path.join(ROOT, path)
    os.makedirs(os.path.dirname(full) or ".", exist_ok=True)
    with open(full, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)


def unquote(v):
    v = v.strip()
    if len(v) >= 2 and v[0] == v[-1] == "'":
        return v[1:-1].replace("''", "'")
    if len(v) >= 2 and v[0] == v[-1] == '"':
        return json.loads(v)
    return v


def frontmatter(text):
    m = re.match(r"^---\r?\n(.*?)\r?\n---\r?\n", text, re.S)
    if not m:
        raise ValueError("no front-matter")
    out = {}
    for line in m.group(1).splitlines():
        km = re.match(r"^([A-Za-z0-9_-]+):\s*(.*)$", line)
        if km:
            out[km.group(1)] = unquote(km.group(2))
    return out


def list_files(rel_dir):
    """Files git will publish: tracked plus untracked-but-not-ignored."""
    try:
        out = subprocess.run(
            ["git", "-C", ROOT, "ls-files", "-co", "--exclude-standard", "--", rel_dir],
            check=True, capture_output=True, text=True, encoding="utf-8",
        ).stdout
        files = [l.strip() for l in out.splitlines() if l.strip()]
    except (OSError, subprocess.CalledProcessError):
        files = []
        for dp, _, fns in os.walk(os.path.join(ROOT, rel_dir)):
            for fn in fns:
                files.append(os.path.relpath(os.path.join(dp, fn), ROOT).replace(os.sep, "/"))
    files = [f for f in files if os.path.isfile(os.path.join(ROOT, f))]
    return sorted(set(files), key=lambda p: (p != rel_dir + "/SKILL.md", p))


def content_hash(files):
    h = hashlib.sha256()
    for f in sorted(files):
        with open(os.path.join(ROOT, f), "rb") as fh:
            data = fh.read().replace(b"\r\n", b"\n")
        h.update(f.encode("utf-8") + b"\0" + hashlib.sha256(data).digest())
    return h.hexdigest()[:12]


def collect():
    skills = []
    for name in sorted(os.listdir(os.path.join(ROOT, "skills"))):
        rel = "skills/" + name
        if not os.path.isfile(os.path.join(ROOT, rel, "SKILL.md")):
            continue
        fm = frontmatter(read(rel + "/SKILL.md"))
        if fm.get("name") != name:
            sys.exit("%s/SKILL.md: front-matter name %r must equal the folder name" % (rel, fm.get("name")))
        if name not in CATEGORIES:
            sys.exit("skill %r has no category: add it to CATEGORIES in scripts/build-catalog.py" % name)
        files = list_files(rel)
        skills.append({
            "name": name,
            "description": " ".join(fm.get("description", "").split()),
            "category": CATEGORIES[name],
            "targets": TARGETS.get(name, DEFAULT_TARGETS),
            "version": content_hash(files),
            "path": rel,
            "raw_url": RAW_BASE + rel + "/SKILL.md",
            "file_count": len(files),
            "files": files,
        })
    missing = set(CATEGORIES) - {s["name"] for s in skills}
    if missing:
        sys.exit("CATEGORIES lists skills that do not exist: " + ", ".join(sorted(missing)))
    skills.sort(key=lambda s: (CATEGORY_ORDER.index(s["category"]), s["name"]))
    return skills


def playbooks():
    out = []
    for fn in sorted(os.listdir(os.path.join(ROOT, "playbooks"))):
        if not fn.endswith(".md") or fn == "README.md":
            continue
        first = read("playbooks/" + fn).splitlines()[0].lstrip("# ").strip()
        out.append((fn, first))
    return out


def build_manifest(skills, updated):
    return {
        "schema_version": 2,
        "name": "agent-skills",
        "description": "Installable agent skills (SKILL.md format) for Claude Code and OpenAI Codex CLI.",
        "repo": REPO_URL,
        "raw_base": RAW_BASE,
        "site": SITE_URL,
        "updated": updated,
        "marketplace": {
            "name": MARKETPLACE,
            "add": "/plugin marketplace add " + SLUG,
            "install": "/plugin install <skill-name>@" + MARKETPLACE,
        },
        "install_paths": {
            "claude_code": "~/.claude/skills/<name>/",
            "claude_code_windows": "%USERPROFILE%\\.claude\\skills\\<name>\\",
            "claude_code_project": ".claude/skills/<name>/",
            "codex": "${CODEX_HOME:-~/.codex}/skills/<name>/",
        },
        "categories": [{"id": c, "title": CATEGORY_TITLES[c], "description": CATEGORY_BLURBS[c]} for c in CATEGORY_ORDER],
        "skills": skills,
    }


def build_marketplace(skills, updated):
    plugins = []
    for s in skills:
        if "claude" not in s["targets"]:
            continue  # Claude Code plugins only carry skills written for Claude Code
        plugins.append({
            "name": s["name"],
            "source": "./",
            "description": s["description"],
            "version": s["version"],
            "category": s["category"],
            "keywords": ["skill", s["category"]],
            "homepage": REPO_URL + "/tree/" + BRANCH + "/" + s["path"],
            "repository": REPO_URL,
            "license": "MIT",
            "skills": ["./" + s["path"]],
        })
    for c in CATEGORY_ORDER:
        members = [s for s in skills if s["category"] == c and "claude" in s["targets"]]
        h = hashlib.sha256("".join(m["version"] for m in members).encode()).hexdigest()[:12]
        plugins.append({
            "name": c + "-pack",
            "source": "./",
            "description": "Bundle of every %s skill: %s" % (c, ", ".join(m["name"] for m in members)),
            "version": h,
            "category": "bundle",
            "keywords": ["bundle", c],
            "homepage": REPO_URL,
            "repository": REPO_URL,
            "license": "MIT",
            "skills": ["./" + m["path"] for m in members],
        })
    return {
        "name": MARKETPLACE,
        "description": "Field-tested engineering-discipline skills: session continuity, verification, data safety, release review, delegation and formatting. One plugin per skill, plus one bundle per category.",
        "version": updated,
        "owner": {"name": "agent-skills maintainers", "url": REPO_URL},
        "plugins": plugins,
    }


def build_llms(skills):
    lines = [
        "# Agent Skills Catalog",
        "",
        "> Installable agent skills in the SKILL.md format for Claude Code (also read by OpenAI Codex CLI). "
        "An agent pointed here should list the catalog, let the user pick, and install only the picks.",
        "",
        "Install protocol: read AGENTS.md first. The machine-readable manifest is skills.json; each entry lists "
        "every file path of the skill, so it can be installed by downloading raw files without git. "
        "Claude Code users can also add this repo as a plugin marketplace "
        "(`/plugin marketplace add %s`, then `/plugin install <skill>@%s`)." % (SLUG, MARKETPLACE),
        "",
        "## Start here",
        "",
        "- [AGENTS.md](%sAGENTS.md): install protocol for agents (list, user picks, install picks only, never overwrite without asking)" % RAW_BASE,
        "- [skills.json](%sskills.json): manifest; skills[] entries carry name, description, category, targets (claude/codex), version, path, raw_url, file_count and files" % RAW_BASE,
        "- [marketplace.json](%s.claude-plugin/marketplace.json): Claude Code plugin marketplace, one plugin per skill plus category bundles" % RAW_BASE,
        "- [README.md](%sREADME.md): human overview and one-line installers" % RAW_BASE,
        "",
    ]
    for c in CATEGORY_ORDER:
        lines.append("## Skills: " + CATEGORY_TITLES[c])
        lines.append("")
        for s in skills:
            if s["category"] == c:
                lines.append("- [%s](%s): %s%s" % (s["name"], s["raw_url"], s["description"],
                                                   TARGET_NOTES.get(tuple(s["targets"]), "").replace("*", "")))
        lines.append("")
    lines.append("## Optional")
    lines.append("")
    lines.append("- [playbooks/README.md](%splaybooks/README.md): index of longer reference docs the skills lean on; read on demand, nothing to install" % RAW_BASE)
    for fn, title in playbooks():
        lines.append("- [%s](%splaybooks/%s): %s" % (fn[:-3], RAW_BASE, fn, title))
    lines.append("- [install.sh](%sinstall.sh): macOS/Linux/Git Bash installer (works piped from curl)" % RAW_BASE)
    lines.append("- [install.ps1](%sinstall.ps1): Windows PowerShell installer (works with irm | iex)" % RAW_BASE)
    lines.append("")
    return "\n".join(lines)


def md_cell(text):
    return text.replace("|", "\\|")


def build_readme(skills, updated, readme):
    block = [README_START, ""]
    for c in CATEGORY_ORDER:
        members = [s for s in skills if s["category"] == c]
        block.append("### %s" % CATEGORY_TITLES[c])
        block.append("")
        block.append("%s Bundle: `%s-pack@%s`." % (CATEGORY_BLURBS[c], c, MARKETPLACE))
        block.append("")
        block.append("| Skill | What it does | Files |")
        block.append("| --- | --- | --- |")
        for s in members:
            block.append("| [%s](%s/SKILL.md) | %s%s | %d |" % (s["name"], s["path"], md_cell(s["description"]),
                                                          TARGET_NOTES.get(tuple(s["targets"]), ""), s["file_count"]))
        block.append("")
    block.append(README_END)
    if README_START not in readme or README_END not in readme:
        sys.exit("README.md is missing the catalog markers")
    head, rest = readme.split(README_START, 1)
    _, tail = rest.split(README_END, 1)
    readme = head + "\n".join(block) + tail
    stats = "<!-- stats -->Last updated: %s · %d skills · %d playbooks<!-- /stats -->" % (
        updated, len(skills), len(playbooks()))
    readme, n = STATS_RE.subn(stats, readme)
    if n != 1:
        sys.exit("README.md is missing the <!-- stats --> marker")
    return readme


def dump(obj):
    return json.dumps(obj, indent=2, ensure_ascii=False) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="exit 1 if generated files are stale")
    ap.add_argument("--date", help="value for the 'updated' stamp (YYYY-MM-DD)")
    args = ap.parse_args()

    skills = collect()
    try:
        old = json.loads(read("skills.json"))
    except (OSError, ValueError):
        old = None
    old_versions = {s["name"]: s.get("version") for s in old.get("skills", [])} if isinstance(old, dict) else {}
    new_versions = {s["name"]: s["version"] for s in skills}
    if args.date:
        updated = args.date
    elif isinstance(old, dict) and old_versions == new_versions and old.get("updated"):
        updated = old["updated"]
    else:
        updated = datetime.date.today().isoformat()

    outputs = {
        "skills.json": dump(build_manifest(skills, updated)),
        ".claude-plugin/marketplace.json": dump(build_marketplace(skills, updated)),
        "llms.txt": build_llms(skills),
        "README.md": build_readme(skills, updated, read("README.md")),
    }
    stale = []
    for path, text in outputs.items():
        try:
            current = read(path)
        except OSError:
            current = None
        if current != text:
            stale.append(path)
            if not args.check:
                write(path, text)
    if args.check:
        if stale:
            print("stale: " + ", ".join(stale) + " (run python3 scripts/build-catalog.py)")
            return 1
        print("catalog up to date")
        return 0
    print("%d skills, updated %s; wrote: %s" % (len(skills), updated, ", ".join(stale) or "nothing (already current)"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
